#!/bin/bash

g++ -O3 -march=native -w -Wall delSig_pt.cpp -rpath `pkg-config --libs-only-L DircObjs | sed -e 's/\-L//g'` `root-config --libs` -I`root-config --incdir` `pkg-config --libs DircObjs` `pkg-config --cflags DircObjs` `pkg-config --cflags tclap` -o ../delSig_pt